name: "Update dependencies version"
author: "kungfu"
description: "Update dependencies version"
inputs:
  token:
    description: "Github token. E.g. secrets.GITHUB_TOKEN"
    require: true
  repo:
    description: "repo"
    require: false
  repo-includes:
    description: "repoIncludes"
    require: false
runs:
  using: "node16"
  main: "dist/index.js"