name: Release - New Version

on:
  pull_request:
    types: [closed]
    branches:
      - alpha/v*/v*
      - release/v*/v*

jobs:
  release:
    uses: kungfu-trader/workflows/.github/workflows/.release-new-version.yml@v1
    with:
      publish-aws-ci: false
      publish-aws-user: false
    secrets:
      GITHUB_PUSH_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
